#!/bin/bash

#===============================================================
# this script creates a new log file and opens it with the 
# chosen editor
#===============================================================

##########
# CONFIG #
##########

EDITOR=micro

##########
# SCRIPT #
##########

PWDOLD=$PWD

cd
if [ ! -d "./logs" ]; then
	mkdir "logs"
fi
cd logs

FLAG="$1"
if [ "$FLAG" == '-s' ]; then
	grep -r --color="always" "$2"
	cd $PWDOLD
	exit 1
elif [ "$FLAG" == '-o' ]; then
	eval $EDITOR "$2.txt"
	cd $PWDOLD
	exit 1
elif [ "$FLAG" == '-l' ]; then
	ls -lh .
	cd $PWDOLD
	exit 1
elif [ "$FLAG" == '-c' ]; then
	touch "$2.txt"
	cd $PWDOLD
	exit 1
elif [ "$FLAG" == '-y' ]; then
	YEST=$(date -d "yesterday" +"%Y-%m-%d.txt")
	eval $EDITOR $YEST
	exit 1
fi


# name log based on curent date
LOGNAME=$(date +"%Y-%m-%d.txt")

# creates new log if one does not already exist for that day
if [ ! -f "./${LOGNAME}" ]; then
	echo "$LOGNAME" | xargs touch
fi

# open log with config'd editor
eval $EDITOR $LOGNAME

# change back to old dir for ~continuity~
cd $PWDOLD
