#!/bin/bash

#===============================================================
# this script creates a new log file and opens it with the 
# chosen editor
#===============================================================

##########
# CONFIG #
##########

EDITOR=micro

##########
# SCRIPT #
##########

PWDOLD=$PWD

cd
if [ ! -d "./logs" ]; then
	mkdir "logs"
fi
cd logs

FLAG="$1"
if [ "$FLAG" == '-s' ]; then
	# search
	grep -r --color="always" "$2"
elif [ "$FLAG" == '-o' ]; then
	# open
	eval $EDITOR "$2.txt"
elif [ "$FLAG" == '-l' ]; then
	# list
	ls -lh .
elif [ "$FLAG" == '-c' ]; then
	# create
	touch "$2.txt"
elif [ "$FLAG" == '-y' ]; then
	# open yesterday
	YEST=$(date -d "yesterday" +"%Y-%m-%d.txt")
	eval $EDITOR $YEST
else
	# main routine, no flags
	# name log based on curent date
	LOGNAME=$(date +"%Y-%m-%d.txt")
	# creates new log if one does not already exist for that day
	if [ ! -f "./${LOGNAME}" ]; then
		echo "$LOGNAME" | xargs touch
	fi
	# open log with config'd editor
	eval $EDITOR $LOGNAME
fi

# change back to old dir for ~continuity~
cd $PWDOLD
exit 1
