#!/bin/bash

#===============================================================
# this script creates a new log file and opens it with the 
# chosen editor
#===============================================================

##########
# CONFIG #
##########

EDITOR=micro

##########
# SCRIPT #
##########

PWDOLD=$PWD

create_log() {
	name=$1
	echo "$name" | xargs touch
	echo $(date +"%A %b %d %Y") >> $name
	s=$(printf "%-80s" "=")
	echo "${s// /=}" >> $name
	echo "" >> $name
}

cd
if [ ! -d "./logs" ]; then
	mkdir "logs"
fi
cd logs

FLAG="$1"
if [ "$FLAG" == '-s' ]; then
	# search
	grep -r --color="always" "$2"
elif [ "$FLAG" == '-o' ]; then
	# open
	eval $EDITOR "$2.txt"
elif [ "$FLAG" == '-l' ]; then
	# list logs
	if [ "$2" == '-a' ]; then
		# list all logs
		ls -t
	elif [ "$2" == '-n' ]; then
		ls -t | head -n "$3"
	else
		# list most recent 5 docs
		ls -t | head -n 5
	fi
elif [ "$FLAG" == '-c' ]; then
	# create
	create_log "$2.txt"
elif [ "$FLAG" == '-y' ]; then
	# open yesterday
	YEST=$(date -d "yesterday" +"%Y-%m-%d.txt")
	eval $EDITOR $YEST
else
	# main routine, no flags
	# name log based on curent date
	LOGNAME=$(date +"%Y-%m-%d.txt")
	# creates new log if one does not already exist for that day
	if [ ! -f "./${LOGNAME}" ]; then
		create_log $LOGNAME
	fi
	# open log with config'd editor
	eval $EDITOR $LOGNAME
fi

# change back to old dir for ~continuity~
cd $PWDOLD
exit 1
